version: '3'

services:

  accounts:
    build: ./accounts/.
    command: python main.py accounts.json
    volumes:
      - ./accounts/.:/accounts
    container_name: accounts

  trasactions:
    build: ./transactions/.
    command: python main.py transactions.json
    volumes:
      - ./transactions/.:/transactions
    container_name: transactions

  authorization:
    build: ./authorization/.
    command: python main.py authorization.json
    volumes:
      - ./authorization/.:/authorization
    ports:
      - "20000:20000"
    container_name: authorization

  apigateway:
    build: ./apigateway/.
    command: python main.py apigateway.json
    volumes:
      - ./apigateway/.:/apigateway
    ports:
      - "10000:10000"
    container_name: apigateway

  nginx:
    image: ./nginx/.
    ports:
      - "443:443"